
all: arxsm arxlnk

arxsm:
	(cd assembler && make $@)

arxlnk:
	(cd linker && make $@)

debug:
	(cd assembler && make $@)
	(cd linker && make $@)

clean:
	(cd assembler && make $@)
	(cd linker && make $@)

